fix(AGOGOS-540): add yamllint to CI
YAML files have been updated to address yamllint warnings.

- rh-pre-commit.version: 2.0.3
- rh-pre-commit.check-secrets: ENABLED

Closes AGOGOS-540

diff --git a/docs/modules/developer-guide/examples/builders/builder.yaml b/docs/modules/developer-guide/examples/builders/builder.yaml
--- a/docs/modules/developer-guide/examples/builders/builder.yaml
+++ b/docs/modules/developer-guide/examples/builders/builder.yaml
@@ -1,3 +1,4 @@
+---
 apiVersion: agogos.redhat.com/v1alpha1
 kind: Builder
 metadata:
@@ -18,35 +19,35 @@ metadata:
   name: my-builder-task
 spec:
   workspaces:
-  - name: pipeline
-  - name: stage
+    - name: pipeline
+    - name: stage
   params:
-  - name: params
-    type: string
+    - name: params
+      type: string
   results:
-  - name: data
-    description: JSON formatted string
+    - name: data
+      description: JSON formatted string
   volumes:
-  - name: config
-    configMap:
-      name: my-builder-config
-      optional: true
-  steps:
-  - name: execute
-    image: registry.access.redhat.com/ubi9-minimal:9.2
-    imagePullPolicy: Always
-    script: |
-      #!/bin/sh -e
-      echo "$1"
-      echo "$2"
-      echo "$3"
-      cat /config/my-builder-config.json
-      echo "Exiting with an error for teaching purposes"
-      exit 1
-    args:
-    - "$(workspaces.pipeline.path)"
-    - "$(results.data.path)"
-    - "$(params.params)"
-    volumeMounts:
     - name: config
-      mountPath: /config
+      configMap:
+        name: my-builder-config
+        optional: true
+  steps:
+    - name: execute
+      image: registry.access.redhat.com/ubi9-minimal:9.2
+      imagePullPolicy: Always
+      script: |
+        #!/bin/sh -e
+        echo "$1"
+        echo "$2"
+        echo "$3"
+        cat /config/my-builder-config.json
+        echo "Exiting with an error for teaching purposes"
+        exit 1
+      args:
+        - "$(workspaces.pipeline.path)"
+        - "$(results.data.path)"
+        - "$(params.params)"
+      volumeMounts:
+        - name: config
+          mountPath: /config
diff --git a/docs/modules/developer-guide/examples/pipelines/stage.yaml b/docs/modules/developer-guide/examples/pipelines/stage.yaml
--- a/docs/modules/developer-guide/examples/pipelines/stage.yaml
+++ b/docs/modules/developer-guide/examples/pipelines/stage.yaml
@@ -41,20 +41,20 @@ metadata:
   name: write-task
 spec:
   workspaces:
-  - name: pipeline
-  - name: stage
+    - name: pipeline
+    - name: stage
   params:
-  - name: config
-    type: string
+    - name: config
+      type: string
   steps:
-  - name: execute
-    image: registry.access.redhat.com/ubi9-minimal:9.2
-    imagePullPolicy: Always
-    script: |
-      #!/bin/sh -e
-      echo "$1" >> $(workspaces.stage.path)/a-simple-file
-    args:
-    - "$(params.config)"
+    - name: execute
+      image: registry.access.redhat.com/ubi9-minimal:9.2
+      imagePullPolicy: Always
+      script: |
+        #!/bin/sh -e
+        echo "$1" >> $(workspaces.stage.path)/a-simple-file
+      args:
+        - "$(params.config)"
 ---
 apiVersion: tekton.dev/v1beta1
 kind: Task
@@ -62,17 +62,17 @@ metadata:
   name: read-task
 spec:
   workspaces:
-  - name: pipeline
-  - name: stage
+    - name: pipeline
+    - name: stage
   params:
-  - name: config
-    type: string
+    - name: config
+      type: string
   steps:
-  - name: execute
-    image: registry.access.redhat.com/ubi9-minimal:9.2
-    imagePullPolicy: Always
-    script: |
-      #!/bin/sh -e
-      ls -lR $(workspaces.pipeline.path)
-      echo "Exiting with an error for teaching purposes"
-      exit 1
+    - name: execute
+      image: registry.access.redhat.com/ubi9-minimal:9.2
+      imagePullPolicy: Always
+      script: |
+        #!/bin/sh -e
+        ls -lR $(workspaces.pipeline.path)
+        echo "Exiting with an error for teaching purposes"
+        exit 1
